(function(){
  let viewer=null;let contracts=[];let sourceDocument="";
  const list=document.getElementById("contractList"),notice=document.getElementById("createNotice");
  const escapeHtml=(v)=>String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");
  const statusName=(s)=>({pending_destination:"بانتظار الوكالة المقابلة",active:"فعّال",rejected:"مرفوض",cancelled:"ملغى"}[s]||s);
  async function api(path,options={}){const response=await fetch(path,{credentials:"same-origin",headers:{"Content-Type":"application/json",...(options.headers||{})},...options});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||"تعذر تنفيذ الطلب.");return data}
  function resize(file){return new Promise((resolve,reject)=>{if(!file?.type.match(/^image\/(jpeg|png|webp)$/))return reject(new Error("اختر صورة JPG أو PNG أو WebP."));const image=new Image(),url=URL.createObjectURL(file);image.onload=()=>{const max=1100,scale=Math.min(1,max/Math.max(image.width,image.height)),canvas=document.createElement("canvas");canvas.width=Math.round(image.width*scale);canvas.height=Math.round(image.height*scale);canvas.getContext("2d").drawImage(image,0,0,canvas.width,canvas.height);URL.revokeObjectURL(url);resolve(canvas.toDataURL("image/jpeg",.76))};image.onerror=()=>reject(new Error("تعذر قراءة الصورة."));image.src=url})}
  async function load(){const q=document.getElementById("contractSearch").value.trim();contracts=(await api("/api/contracts"+(q?"?q="+encodeURIComponent(q):""))).contracts;render()}
  function render(){if(!contracts.length){list.innerHTML='<p class="meta">لا توجد عقود مطابقة.</p>';return}list.innerHTML=contracts.map(c=>{const canRespond=viewer.role==="agent"&&viewer.agencyId===c.destination_agency_id&&c.status==="pending_destination";return '<article class="contract-card"><h3>'+escapeHtml(c.title)+'</h3><div class="contract-meta"><b>'+escapeHtml(c.contract_number)+'</b><span>المرجع: '+escapeHtml(c.reference_number)+'</span><span>'+escapeHtml(c.source_agency_name)+' ←→ '+escapeHtml(c.destination_agency_name)+'</span><span class="status '+escapeHtml(c.status)+'">'+statusName(c.status)+'</span><span>التاريخ: '+new Date(c.created_at).toLocaleString("ar")+'</span></div><details><summary>عرض البنود والإثباتات</summary><p style="white-space:pre-wrap">'+escapeHtml(c.terms)+'</p><div class="document-grid"><div><b>إثبات الوكالة المنشئة</b><img src="'+c.source_identity_document+'" alt="إثبات الوكالة المنشئة" /></div>'+(c.destination_identity_document?'<div><b>إثبات الوكالة المقابلة</b><img src="'+c.destination_identity_document+'" alt="إثبات الوكالة المقابلة" /></div>':'')+'</div></details><div class="actions"><button type="button" data-print="'+c.id+'">طباعة العقد</button>'+(canRespond?'<button type="button" data-accept="'+c.id+'">قبول وإرفاق الإثبات</button><button type="button" class="danger" data-reject="'+c.id+'">رفض</button>':'')+'</div>'+(c.rejected_reason?'<p>سبب الرفض: '+escapeHtml(c.rejected_reason)+'</p>':'')+'</article>'}).join("")}
  document.getElementById("sourceIdentity").addEventListener("change",async e=>{try{sourceDocument=await resize(e.target.files[0])}catch(err){alert(err.message)}});
  document.getElementById("contractForm").addEventListener("submit",async e=>{e.preventDefault();try{if(!sourceDocument)throw new Error("أرفق صورة إثبات مدني أولاً.");const data=await api("/api/contracts",{method:"POST",body:JSON.stringify({destinationAgencyId:document.getElementById("destinationAgencyId").value.trim(),title:document.getElementById("contractTitle").value.trim(),terms:document.getElementById("contractTerms").value.trim(),identityDocument:sourceDocument})});notice.hidden=false;notice.textContent=data.message+" رقم العقد: "+data.contractNumber;e.target.reset();sourceDocument="";await load()}catch(err){alert(err.message)}});
  document.getElementById("searchForm").addEventListener("submit",e=>{e.preventDefault();load().catch(err=>alert(err.message))});
  list.addEventListener("click",async e=>{const id=e.target.dataset.print||e.target.dataset.accept||e.target.dataset.reject;if(!id)return;const c=contracts.find(x=>x.id===id);try{if(e.target.dataset.print){document.getElementById("printSheet").innerHTML='<h1>عقد إلكتروني بين وكالتين</h1><h2>'+escapeHtml(c.title)+'</h2><p><b>رقم العقد:</b> '+escapeHtml(c.contract_number)+'</p><p><b>الرقم المرجعي:</b> '+escapeHtml(c.reference_number)+'</p><p><b>الطرف الأول:</b> '+escapeHtml(c.source_agency_name)+'</p><p><b>الطرف الثاني:</b> '+escapeHtml(c.destination_agency_name)+'</p><h3>بنود العقد</h3><p style="white-space:pre-wrap">'+escapeHtml(c.terms)+'</p><p><b>الحالة:</b> '+statusName(c.status)+'</p><div class="documents"><img src="'+c.source_identity_document+'" />'+(c.destination_identity_document?'<img src="'+c.destination_identity_document+'" />':'')+'</div>';window.print();return}if(e.target.dataset.reject){const reason=prompt("سبب رفض العقد:");if(!reason)return;await api("/api/contracts/"+id+"/respond",{method:"POST",body:JSON.stringify({decision:"reject",reason})})}else{const input=document.createElement("input");input.type="file";input.accept="image/jpeg,image/png,image/webp";input.onchange=async()=>{try{const doc=await resize(input.files[0]);const data=await api("/api/contracts/"+id+"/respond",{method:"POST",body:JSON.stringify({decision:"accept",identityDocument:doc})});alert(data.message);await load()}catch(err){alert(err.message)}};input.click();return}await load()}catch(err){alert(err.message)}});
  (async()=>{try{viewer=(await api("/api/auth/status")).user;if(viewer?.role==="agent")document.getElementById("createSection").hidden=false;await load()}catch(err){list.innerHTML='<p class="notice">'+escapeHtml(err.message)+'</p>'}})();
})();
